NonLeague/Models/ErrorViewModel.cs
using System;

namespace NonLeague.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NonLeague/Models/League.cs
namespace NonLeague.Models
{
    public class League
    {
        public string Competition { get; set; }
        public int Step { get; set; }  
        public int CompetitionID { get; set; } 
    }   
}

NonLeague/Models/LeagueTableRoot.cs
using System.Collections.Generic;

namespace NonLeague.Models
{
    public class Team
    {
        public string Position { get; set; }
        public string Name { get; set; }
        public string Played { get; set; }
        public string Won { get; set; }
        public string Drawn { get; set; }
        public string Lost { get; set; }
        public string For { get; set; }
        public string Against { get; set; }
        public string GoalDifference { get; set; }
        public string Points { get; set; }
    }

    public class LeagueTable
    {
        public string Competition { get; set; }
        public string Description { get; set; }
        public List<Team> Team { get; set; }
    }

    public class LeagueTableRoot
    {
        public LeagueTable LeagueTable { get; set; }
    }
    
}

NonLeague/Models/MatchesCompetitionRoot.cs
using System.Collections.Generic;

namespace NonLeague.Models
{
    public class Match
    {
        public string Date { get; set; }
        private string _time;
        public string Time { 
            get => this._time;
            set => this._time = value.Length <= 5 ? value : value.Substring(0, 5);
        }
        public string Status { get; set; }
        public string HomeTeamName { get; set; }
        public int HomeTeamHalfTimeScore { get; set; }
        public int HomeTeamScore { get; set; }
        public string AwayTeamName { get; set; }
        public int AwayTeamHalfTimeScore { get; set; }
        public int AwayTeamScore { get; set ;}
        public int Attendance { get; set; }
    }

    public class MatchesCompetition
    {
        public string Competition { get; set; }
        public string Description { get; set; }
        public List<Match> Match { get; set; }
    }

    public class MatchesCompetitionRoot
    {
        public MatchesCompetition MatchesCompetition { get; set; }
    }
    
}

NonLeague/Models/Month.cs
namespace NonLeague.Models
{
    public class Month
    {
        public string Name { get; set; }
        public int ID { get; set; }
    }

    
}

NonLeague/ViewModels/LeagueSeason.cs
using System.Collections.Generic;
using NonLeague.Models;

namespace NonLeague.ViewModels
{
    public class LeagueSeason
    {
        public int CompetitionID { get; set; }
        public string Competition { get; set; }
        public IEnumerable<Month> Season { get; set; }

    }
}

NonLeague/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace NonLeague.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {   
            return View();
        }

    }
}

NonLeague/Controllers/CompetitionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using NonLeague.Models;
using NonLeague.Services;

namespace NonLeague.Controllers
{
    public class CompetitionController : Controller
    {
        private readonly ILeagueService _leagueService;
        private readonly IHostingEnvironment _hostingEnvironment;
        
        public CompetitionController(ILeagueService leagueService, IHostingEnvironment hostingEnvironment)
        {
            _leagueService = leagueService;
            _hostingEnvironment = hostingEnvironment;
        }

        [Route("fixturesandresults")]
        [Route("")]
        public IActionResult FixturesAndResults()
        {            
            var model = _leagueService.GetAll(_hostingEnvironment.WebRootPath);

            return View(model);
        }

        [Route("tables")]
        public IActionResult Table()
        {
            var model = _leagueService.GetAll(_hostingEnvironment.WebRootPath);

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NonLeague/Controllers/MatchController.cs
using Microsoft.AspNetCore.Mvc;
using NonLeague.Services;
using System.Threading.Tasks;

namespace NonLeague.Controllers
{
    public class MatchController : Controller
    {
        private readonly IMatchService _matchService;
        
        public MatchController(IMatchService matchService)
        {
            _matchService = matchService;
        }
        
        [Route("fixturesandresults/season/details")]
        [HttpGet("{competitionid:int}")]
        [HttpGet("{monthid:int}")]
        public async Task<IActionResult> Index(int competitionID, int monthID)
        {
            return View(await _matchService.GetFixturesForMonth(competitionID, monthID));
        }
        
    }
}

NonLeague/Controllers/MatchThisWeekController.cs
using Microsoft.AspNetCore.Mvc;
using NonLeague.Services;
using System.Threading.Tasks;

namespace NonLeague.Controllers
{
    public class MatchThisWeekController : Controller
    {
        private readonly IMatchService _matchService;
        
        public MatchThisWeekController(IMatchService matchService)
        {
            _matchService = matchService;
        }
        
        [Route("fixturesandresults/today")]
        public async Task<IActionResult> Index()
        {
            return View(await _matchService.GetFixturesForToday());
        }
        
    }
}

NonLeague/Controllers/SeasonController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using NonLeague.ViewModels;
using NonLeague.Services;

namespace NonLeague.Controllers
{
    public class SeasonController : Controller
    {
        private readonly ISeasonService _seasonService;
        private readonly ILeagueService _leagueService;
        private readonly IHostingEnvironment _hostingEnvironment;

        public SeasonController(ISeasonService seasonService, ILeagueService leagueService, IHostingEnvironment hostingEnvironment)
        {
            _seasonService = seasonService;
            _leagueService = leagueService;
            _hostingEnvironment = hostingEnvironment;
        }

        [Route("fixturesandresults/[controller]")]
        [HttpGet("{competitionID:int}")]
        public IActionResult Index(int competitionID)
        {
            var leagueSeason = new LeagueSeason
            {
                CompetitionID = competitionID,
                Competition = _leagueService.GetCompetition(competitionID, _hostingEnvironment.WebRootPath),
                Season = _seasonService.GetSeason(_hostingEnvironment.WebRootPath)
            };

            return View(leagueSeason);
        }

    }
}

NonLeague/Controllers/TableController.cs
using Microsoft.AspNetCore.Mvc;
using NonLeague.Services;
using System.Threading.Tasks;

namespace NonLeague.Controllers
{
    public class TableController : Controller
    {
        private readonly ITableService _leagueTableService;
        
        public TableController(ITableService leagueTableService)
        {
            _leagueTableService = leagueTableService;
        }
        
        [Route("tables/details")]
        [HttpGet("{competitionID:int}")]
        public async Task<IActionResult> Index(int competitionID)
        {
            return View(await _leagueTableService.GetTable(competitionID));
        }
        
    }
}

NonLeague/Views/About/Index.cshtml
<h3>About</h3>
<hr />
<div class="container">
    <h4>I'm Andy Bowskill. I'm a software developer and a stroke survivor.</h4>
    <p>I've written this non-league football website using C# and ASP.NET Core. An alternative to, and defunct, the 'Non League' iOS app.</p>
    <p>Please feel free to contact me at <a href="https://www.andybowskill.co.uk/">www.andybowskill.co.uk</a>.</p>
    <hr />
    <p class="text-center">If you find this non-league football website useful, please buy me a coffee:</p>
    <p class="text-center"><link href="https://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext" rel="stylesheet"><a class="bmc-button" target="_blank" href="https://www.buymeacoffee.com/andybowskill"><img src="https://www.buymeacoffee.com/assets/img/BMC-btn-logo.svg" alt="Buy me a coffee"><span style="margin-left:5px">Buy me a coffee</span></a></p>
</div>

NonLeague/Views/Competition/FixturesAndResults.cshtml
@model IEnumerable<NonLeague.Models.League>
@{
    int step = 0;
}

<h3>Fixtures / Results</h3>
<hr />
<div class="list-group">
    <a asp-controller="MatchThisWeek" asp-action="Index" class="list-group-item">
        <p class="list-group-item-heading">Today</p>
    </a>
</div>
<hr />
<div class="list-group">
    @foreach (var league in Model)
    {
        @if (step != @league.Step)
        {
            <h4>Step @league.Step</h4>
            step = @league.Step;
        }
            <a asp-controller="Season" asp-action="Index" asp-route-competitionid=@league.CompetitionID class="list-group-item">
                <p class="list-group-item-heading">@league.Competition</p>
            </a>
    }
</div>

NonLeague/Views/Competition/Match.cshtml
@model IEnumerable<NonLeague.Models.League>
@{
    ViewData["Title"] = "Fixture / Results";
    int step = 0;
}

<h3>Fixtures / Results</h3>
<hr />
<div class="list-group">
    <a asp-controller="MatchThisWeek" asp-action="Index" class="list-group-item">
        <p class="list-group-item-heading">Today</p>
    </a>
</div>
<hr />
<div class="list-group">
    @foreach (var league in Model)
    {
        @if (step != @league.Step)
        {
            <h4>Step @league.Step</h4>
            step = @league.Step;
        }
            <a asp-controller="Season" asp-action="Index" asp-route-compid=@league.CompetitionID class="list-group-item">
                @if (league.Division == "")
                {
                    <p class="list-group-item-heading">@league.Name</p>
                }
                else
                {
                    <p class="list-group-item-heading">@league.Name - @league.Division</p>
                }
                <p class="list-group-item-text">@league.Sponsor</p>
            </a>
    }
</div>

NonLeague/Views/Competition/Table.cshtml
@model IEnumerable<NonLeague.Models.League>
@{
    int step = 0;
}

<h3>Tables</h3>
<hr />

<div class="list-group">
    @foreach (var league in Model)
    {
        @if (step != @league.Step)
        {
            <h4>Step @league.Step</h4>
            step = @league.Step;
        }
            <a asp-controller="Table" asp-action="Index" asp-route-competitionid=@league.CompetitionID class="list-group-item">
                <p class="list-group-item-heading">@league.Competition</p>
            </a>
    }
</div>

NonLeague/Views/Match/Index.cshtml
@model NonLeague.Models.MatchesCompetition
@{
    string validDate = null;
}

<h3>Fixtures / Results</h3>
<hr />
<h3>@Model.Competition</h3>

<table class="table table-condensed no-gutters-horizontal">
    @foreach (var match in Model.Match)
    {
        @if (validDate != @match.Date)
        {
            validDate = @match.Date;
            <tr>
                <th colspan="3">
                    <h4>@match.Date</h4>
                </th>
            </tr>

        }

        bool inProgress = !@match.Status.Contains("Kick off");

            <tr>
                <td class="text-right">@match.HomeTeamName</td>
                @if (inProgress)
                {
                    <td class="text-center bold">@match.HomeTeamScore - @match.AwayTeamScore</td>
                }
                else
                {
                    <td class="text-center bold">@match.Time</td>
                }
                <td class="text-left">@match.AwayTeamName</td>
            </tr>

        @if (inProgress)
        {
            <tr>
                <td class="text-right text-muted muted">@match.Status</td>
                <td class="text-center text-muted muted">@match.HomeTeamHalfTimeScore - @match.AwayTeamHalfTimeScore</td>

                @if (@match.Attendance > 0)
                {
                    <td class="text-left text-muted muted">Attendance: @match.Attendance</td>
                }
                else
                {
                    <td class="text-left text-muted muted"></td>
                }
            </tr>
        }

    }
</table>

NonLeague/Views/MatchThisWeek/Index.cshtml
@model List<NonLeague.Models.MatchesCompetition>
@{
    string firstLeague = null;
    string validDate = null;
    int leagueHeaderID = 0;
    int leagueBodyID = 0;
}

<h3>Fixtures / Results</h3>
<hr />

<ul class="nav nav-pills" role="tablist">
    <li role="presentation" class="dropdown">
        <a href="#" class="dropdown-toggle" id="dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><h4>League <span class="caret"></span></h4></a>

        <ul class="dropdown-menu" id="dropdown" aria-labelledby="dropdown">
            <li><a data-scroll href="#league-@(++leagueHeaderID)">Vanarama National League</a></li>
            <li role="separator" class="divider"></li>
            <li><a data-scroll href="#league-@(++leagueHeaderID)">Vanarama National League North</a></li>
            <li><a data-scroll href="#league-@(++leagueHeaderID)">Vanarama National League South</a></li>
            <li role="separator" class="divider"></li>
            <li><a data-scroll href="#league-@(++leagueHeaderID)">Evo-Stik League Premier Division</a></li>
            <li><a data-scroll href="#league-@(++leagueHeaderID)">Evo-Stik Southern Premier Central</a></li>
            <li><a data-scroll href="#league-@(++leagueHeaderID)">Evo-Stik Southern Premier South</a></li>
            <li><a data-scroll href="#league-@(++leagueHeaderID)">Bostik League Premier Division</a></li>
            <li role="separator" class="divider"></li>
            <li><a data-scroll href="#league-@(++leagueHeaderID)">Evo-Stik League First Division East</a></li>
            <li><a data-scroll href="#league-@(++leagueHeaderID)">Evo-Stik League First Division West</a></li>
            <li><a data-scroll href="#league-@(++leagueHeaderID)">Evo-Stik Southern Division One Central</a></li>
            <li><a data-scroll href="#league-@(++leagueHeaderID)">Evo-Stik Southern Division One South</a></li>
            <li><a data-scroll href="#league-@(++leagueHeaderID)">Bostik League North Division</a></li>
            <li><a data-scroll href="#league-@(++leagueHeaderID)">Bostik League South Central Division</a></li>
            <li><a data-scroll href="#league-@(++leagueHeaderID)">Bostik League South East Division</a></li>
        </ul>
    </li>
</ul>

<hr />

<table class="table table-condensed no-gutters-horizontal">
    @foreach (var league in Model)
    {
        @if (leagueBodyID == 0)
        {
            firstLeague = "first";
        }
        else
        {
            firstLeague = null;
        }

        <tr id="league-@(++leagueBodyID)">
            <th colspan="3">
                <h3 class=@firstLeague>@league.Competition</h3>
            </th>
        </tr>

        @foreach (var match in league.Match)
        {
            @if (validDate != @match.Date)
            {
                validDate = @match.Date;
                <tr>
                    <th colspan="3">
                        <h4>@match.Date</h4>
                    </th>
                </tr>
            }

            bool inProgress = !@match.Status.Contains("Kick off");

            <tr>
                <td class="text-right">@match.HomeTeamName</td>
                @if (inProgress)
                {
                    <td class="text-center bold">@match.HomeTeamScore - @match.AwayTeamScore</td>
                }
                else
                {
                    <td class="text-center bold">@match.Time</td>
                }
                <td class="text-left">@match.AwayTeamName</td>
            </tr>

            @if (inProgress)
            {
                <tr>
                    <td class="text-right text-muted muted">@match.Status</td>
                    <td class="text-center text-muted muted">@match.HomeTeamHalfTimeScore - @match.AwayTeamHalfTimeScore</td>

                    @if (@match.Attendance > 0)
                    {
                        <td class="text-left text-muted muted">Attendance: @match.Attendance</td>
                    }
                    else
                    {
                        <td class="text-left text-muted muted"></td>
                    }
                </tr>
            }
        }
    }
</table>

NonLeague/Views/Season/Index.cshtml
@model NonLeague.ViewModels.LeagueSeason

<h3>Fixtures / Results</h3>
<hr />
<h3>@Model.Competition</h3>

<div class="list-group">
@foreach(var month in Model.Season)
{
  <a asp-controller="Match" asp-action="Index" asp-route-competitionid=@Model.CompetitionID asp-route-monthid=@month.ID class="list-group-item">
    <p class="list-group-item-heading">@month.Name</p>
  </a>
}
</div>

NonLeague/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Non-League Football in England, UK</title>
    <meta name="description" content="Non-league football in England, UK. Grassroots football fixtures, results and tables covering steps one, two, three and four." />
    <meta name="author" content="Andy Bowskill">

    <meta property="og:title" content="Non-League Football in England, UK" />
    <meta property="og:description" content="Non-league football in England, UK. Grassroots football fixtures, results and tables covering steps one, two, three and four." />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://www.nonleaguefootball.info/" />
    <meta property="og:image" content="/screenshot.jpg" />
    <meta property="og:site_name" content="Non-League Football in England, UK">

    <environment include="Development">
        <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link href="https://fonts.googleapis.com/css?family=Bangers|Montserrat" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="competition" asp-action="fixturesandresults" class="navbar-custom navbar-brand">Non-League Football</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="competition" asp-action="fixturesandresults">Fixtures / Results</a></li>
                    <li><a asp-area="" asp-controller="competition" asp-action="table">Tables</a></li>
                    <li><a asp-area="" asp-controller="about" asp-action="index">About</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
    </div>

    <footer>
        <hr />
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <p class="text-center text-muted">2019 &copy; Non-League Football</p>
                </div>
            </div>
       </div>
     </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

NonLeague/Views/Table/Index.cshtml
@model NonLeague.Models.LeagueTable

<h3>Tables</h3>
<hr />
<h3>@Model.Competition</h3>
<table class="table table-striped table-bordered table-condensed no-gutters-horizontal">
    <tr>
        <th>Pos.</th>
        <th>Team</th>
        <th class="text-center">P</th>
        <th class="text-center">W</th>
        <th class="text-center">D</th>
        <th class="text-center">L</th>
        <th class="text-center">GD</th>
        <th class="text-center">Pts.</th>

    </tr>
@foreach (var team in Model.Team)
{
    <tr>
        <td>@team.Position</td>
        <td>@team.Name</td>
        <td class="text-center">@team.Played</td>
        <td class="text-center">@team.Won</td>
        <td class="text-center">@team.Drawn</td>
        <td class="text-center">@team.Lost</td>
        <td class="text-center">@team.GoalDifference</td>
        <td class="text-center">@team.Points</td>
    </tr>
}
</table>